"""
CIC-IDS-2017 Data Loader
========================
Handles the well-known data-quality issues in the MachineLearningCSV
distribution of CIC-IDS-2017 (generated by CICFlowMeter):

1.  Column names have spaces, mixed case, "/" and "." characters.
    Normalised to lowercase_with_underscores.

2.  Label column is often " Label" (with a leading space). Stripped.

3.  Flow Bytes/s and Flow Packets/s contain Inf values when duration=0.
    Replaced with NaN then filled 0.

4.  Many numeric columns contain NaN. Filled with 0 after coercion.

5.  Negative values in Fwd/Bwd Header Length — CICFlowMeter overflow bug.
    NOT clipped here; grammar constraints will flag them (correct behaviour).

6.  Monday file contains only benign traffic — included for calibration.

7.  Encoding: UTF-8 first, then latin-1 fallback.

8.  Folder name auto-detected: CICIDS2017, cicids2017, MachineLearningCSV
    all accepted.
"""

from __future__ import annotations
from pathlib import Path
from typing import Optional
import sys

import numpy as np
import pandas as pd

from config import (
    DATA_RAW,
    DATA_PROCESSED,
    CICIDS_FILES,
    CICIDS_LABEL_COL,
    CICIDS_BENIGN_STR,
    CICIDS_NORMAL_PARQUET,
    CICIDS_FULL_PARQUET,
    CICIDS_TRAIN_PARQUET,
    CICIDS_TEST_PARQUET,
    VERBOSE,
)


def _log(msg: str) -> None:
    if VERBOSE:
        print(f"[cicids] {msg}", flush=True)


def _normalise_colname(name: str) -> str:
    """Normalise a CICFlowMeter column name to a clean identifier."""
    s = str(name).strip().lower()
    s = s.replace("/", "_per_")
    s = s.replace(".", "_")
    s = s.replace(" ", "_")
    while "__" in s:
        s = s.replace("__", "_")
    return s.strip("_")


def _find_cicids_dir() -> Optional[Path]:
    """Find the CICIDS folder under data/raw/ — case-insensitive."""
    for candidate in ("CICIDS2017", "cicids2017", "MachineLearningCSV",
                      "CIC-IDS-2017", "cic-ids-2017", "CICIDS-2017"):
        p = DATA_RAW / candidate
        if p.exists():
            return p
    return None


def get_cicids_dir() -> Path:
    d = _find_cicids_dir()
    if d is None:
        raise FileNotFoundError(
            f"\n  CIC-IDS-2017 files not found under {DATA_RAW}/\n"
            f"  Create data/raw/CICIDS2017/ and place the 8 _ISCX.csv files.\n"
            f"  Download: https://www.unb.ca/cic/datasets/ids-2017.html\n"
        )
    return d


def _load_one_csv(path: Path) -> pd.DataFrame:
    for enc in ("utf-8", "latin-1", "cp1252"):
        try:
            df = pd.read_csv(path, encoding=enc, low_memory=False,
                             on_bad_lines="skip")
            break
        except UnicodeDecodeError:
            continue
    else:
        raise RuntimeError(f"Cannot decode {path}")

    df.columns = [_normalise_colname(c) for c in df.columns]

    # Locate label column
    if CICIDS_LABEL_COL not in df.columns:
        for cand in ("label", "attack", "class"):
            if cand in df.columns:
                df = df.rename(columns={cand: CICIDS_LABEL_COL})
                break
        if CICIDS_LABEL_COL not in df.columns:
            raise KeyError(
                f"Label column not found in {path.name}. "
                f"Columns: {df.columns.tolist()[:10]}"
            )

    df[CICIDS_LABEL_COL] = (
        df[CICIDS_LABEL_COL].astype(str).str.strip().str.lower()
    )

    # Drop identifier columns
    df = df.drop(columns=[c for c in
                           ("flow_id", "source_ip", "destination_ip",
                            "src_ip", "dst_ip", "timestamp")
                           if c in df.columns], errors="ignore")

    # Replace Inf, fill NaN
    num = df.select_dtypes(include=[np.number]).columns
    df[num] = df[num].replace([np.inf, -np.inf], np.nan).fillna(0)

    # Binary label
    df["label_binary"] = (df[CICIDS_LABEL_COL] != CICIDS_BENIGN_STR).astype(int)
    return df


def load_cicids_raw(files: Optional[list[str]] = None,
                    use_cache: bool = True) -> pd.DataFrame:
    """Load and concatenate CIC-IDS-2017 CSVs."""
    if use_cache and CICIDS_FULL_PARQUET.exists():
        _log(f"loading cache: {CICIDS_FULL_PARQUET}")
        return pd.read_parquet(CICIDS_FULL_PARQUET)

    cdir = get_cicids_dir()
    if files is None:
        files = CICIDS_FILES

    frames = []
    for fname in files:
        fpath = cdir / fname
        if not fpath.exists():
            _log(f"WARNING: {fname} not found — skipping")
            continue
        _log(f"reading {fname} ...")
        df = _load_one_csv(fpath)
        _log(f"  {df.shape}  benign={int((df['label_binary']==0).sum()):,}  "
             f"attack={int((df['label_binary']==1).sum()):,}")
        frames.append(df)

    if not frames:
        raise FileNotFoundError("No CIC-IDS-2017 files loaded.")

    df_full = pd.concat(frames, ignore_index=True)
    _log(f"concatenated: {df_full.shape}")

    if use_cache:
        df_full.to_parquet(CICIDS_FULL_PARQUET, index=False)
    return df_full


def load_cicids_normal(use_cache: bool = True) -> pd.DataFrame:
    """Return benign rows only (for grammar calibration)."""
    if use_cache and CICIDS_NORMAL_PARQUET.exists():
        _log(f"loading cache: {CICIDS_NORMAL_PARQUET}")
        return pd.read_parquet(CICIDS_NORMAL_PARQUET)

    df = load_cicids_raw(use_cache=use_cache)
    normal = df[df["label_binary"] == 0].copy().reset_index(drop=True)
    _log(f"normal rows: {len(normal):,}")
    if use_cache:
        normal.to_parquet(CICIDS_NORMAL_PARQUET, index=False)
    return normal


def load_cicids_train_test(use_cache: bool = True) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Mon–Thu = train, Fri = test (standard CIC-IDS-2017 convention)."""
    if use_cache and CICIDS_TRAIN_PARQUET.exists() and CICIDS_TEST_PARQUET.exists():
        _log("loading cached train/test")
        return (pd.read_parquet(CICIDS_TRAIN_PARQUET),
                pd.read_parquet(CICIDS_TEST_PARQUET))

    cdir = get_cicids_dir()
    train_f, test_f = [], []
    for df_frames, fnames in ((train_f, [f for f in CICIDS_FILES if not f.startswith("Friday")]),
                              (test_f,  [f for f in CICIDS_FILES if f.startswith("Friday")])):
        for fname in fnames:
            fpath = cdir / fname
            if fpath.exists():
                df_frames.append(_load_one_csv(fpath))

    train_df = pd.concat(train_f, ignore_index=True)
    test_df  = pd.concat(test_f,  ignore_index=True)
    _log(f"train={train_df.shape}  test={test_df.shape}")

    if use_cache:
        train_df.to_parquet(CICIDS_TRAIN_PARQUET, index=False)
        test_df.to_parquet(CICIDS_TEST_PARQUET,   index=False)
    return train_df, test_df


if __name__ == "__main__":
    try:
        df = load_cicids_raw()
        print(f"Loaded {df.shape}  benign={int((df['label_binary']==0).sum()):,}")
    except FileNotFoundError as e:
        print(e)
        sys.exit(1)
